### ISSUE TITLE
Handle miniatures by packets instead of existing server side

### ISSUE THREAD

**Issue by GalacticStar123** [MiniaturePets/MiniaturePets#101]
*Suggestion:* 
Only send the packet of the miniature to the clients and not having them exist server side
*How will it improve the plugin:* 
really important performance improvements and prevents miniature armorstands from staying in the world when the server crashes

**Comment by Amokinio** [comment]
Hi @GalacticStar123, I'll let NacOJerk review this suggestion, Personally I do think that it could be done but I'm not sure about the complexity of implementing this in comparison with the current system.

**Comment by NacOJerk** [comment]
That does sound like a great idea I will have to take a deeper look again into the MC protocol, this is though a huge change in the way mpet works so I will probably only do it on the next big mpet update (V2.5/V3.0)

**Comment by Govindass** [comment]
this is a really great suggestion, I have been thinking of the same for a while. but once it gets made, you should make an API method to spawn it packet/normal, so for stuff like MythicMobs there don't be weird conflicts

**Comment by liorsl** [comment]
Hi,
Thanks a lot for the suggestion. Recently, we have moved to use another API for reflections, that will significantly improve performance. As your suggestion is very complicated to implement, I will have to close it.
