### ISSUE TITLE
Pet Lock

### ISSUE THREAD

**Issue by Hipopotofobia** [miniaturepets/miniaturepets#103]
*Suggestion:* Pet Lock

*How will it improve the plugin:*
- Pet locking will allow the user to leave a pet in a certain area without having it follow them. This would allow for easier modeling as you will be able to see a 360 view of the pet. 

*Any examples or additional information:*
- If that player logs out or switches worlds, the pet should be removed. 
- An option should be in the config if the player gets "x" blocks away from the pet, the pet should be removed.

**Comment by Amokinio** [comment]
Hello, thank you very much for your suggestion, I've sent it forward, in case any updates will come, you will be the first to know.

**Comment by NacOJerk** [comment]
This feature already exists and it called sit (/mpet sit)
