### ISSUE TITLE
Display error；MySQL is also unavailable

### ISSUE THREAD

**Issue by 1425115471** [miniaturepets/miniaturepets#104]
spigot-1.12.2
MiniaturePets2.2.1
MySQL is also unavailable
![EZOY@()_O1E9I7)8E$N48YR](https://user-images.githubusercontent.com/29402452/60403607-06bd0880-9bd2-11e9-9f39-e4ef7f088843.png)

**Comment by NacOJerk** [comment]
Please provide a mpet dump

**Comment by 1425115471** [comment]
dump ？

**Comment by NacOJerk** [comment]
do /mpet dump

**Comment by 1425115471** [comment]
Failure to use MySQL is secondary



The main thing is to keep things, as shown in the picture.

**Comment by 1425115471** [comment]
Pets will always be in the air

**Comment by NacOJerk** [comment]
We still need /mpet dump

**Comment by 1425115471** [comment]
Is it an error file?

**Comment by NacOJerk** [comment]
it is a paste containing information about the server

**Comment by NacOJerk** [comment]
Without it we don't provide support

**Comment by Amokinio** [comment]
@1425115471 Just run `/mpet dump` on your server, it will provide you with a link, as soon as you get it paste it here and tag NacOJerk.

**Comment by 1425115471** [comment]
好的

**Comment by 1425115471** [comment]
https://pastebin.com/hcmvUku7

**Comment by NacOJerk** [comment]
This could be an issue with the .mpet file does this occur with all pets ?

**Comment by 1425115471** [comment]
Yes, when I randomly send it to a place, there's a high probability that it will happen.
Pets are decomposed in the air, and pets can't move.

**Comment by 1425115471** [comment]
I've bought several pets. That's the case.

**Comment by NacOJerk** [comment]
Are the pets fixed after a few seconds or do they stay like this ?
