### ISSUE TITLE
Pet stays in spawn forever on player logout

### ISSUE THREAD

**Issue by Kira07** [miniaturepets/miniaturepets#105]
*Short description:* Pet stays in spawn forever

*Long description:* My spawn is filled with pet which never despawns, maybe because of the mob-spawning deny flag or I don't know

*Actions to repeat / ways of reaching the bug:* Summon your pet in spawn, then logout, it oftens stays there forever, the pet should be force-despawned on logout to prevent this from happening

*Miniature Pets Dump Link:* https://pastebin.com/MnnFei0e

**Comment by NacOJerk** [comment]
Can you please repost the mpet dump
