### ISSUE TITLE
pet interaction Menu bug

### ISSUE THREAD

**Issue by saintdevin** [miniaturepets/miniaturepets#106]
*Short description:* Hopper menu for pet interaction removes items from player's inventory

*Long description:* The Hopper menu that is used for the pet interactions menu will remove items from a players hotbar when they right click on their pet. it happens often but not 100% of the time. sometimes it just moves the items further down the hotbar instead. Disabling the hopper gui in the config file fixes the issue.

*Actions to repeat / ways of reaching the bug:* right clicking your pet with items in your hotbar

*Miniature Pets Dump Link:*

**Comment by Amokinio** [comment]
Hello, please add your dump link and possible a GIF/video of this happening, it would help us a lot.

**Comment by NacOJerk** [comment]
Thank you for sending us the issue we have fixed in the newer version

**Comment by Amokinio** [comment]
This issue has been reopened by @hahaleks, dump link: https://pastebin.com/Lwc6EvtZ

**Comment by Amokinio** [comment]
@NacOJerk

**Comment by NacOJerk** [comment]
I am no longer able to recreate the issue. Please provide a gif or video showing it

**Comment by Amokinio** [comment]
Hi, due to lack of response this issue is now closed, if you have anything to add or would like to reopen please do so.

Closed
