### ISSUE TITLE
Rename command language bug.

### ISSUE THREAD

**Issue by OGreenC** [miniaturepets/miniaturepets#108]
*Short description:* 
I can't seem to find the language string which is displayed when a player is attempting to rename a pet, but is using too many chars.

*Long description:* 
Is this message configuable? and if so, where? :-)
It also seems like the there's some problems with the color codes.

*Actions to repeat / ways of reaching the bug:* 
Spawn a pet, and attempt to give it a too long name.
This is what it looks like in the chat:
https://gyazo.com/6db5df75e868217eaba20c101d332ff4

*Miniature Pets Dump Link:*

**Comment by Amokinio** [comment]
Thank you for this bug report, I'll send it over to development team.

**Comment by NacOJerk** [comment]
Thank you for reporting this issue, it led  me to find more issues and fix them :smile:
