### ISSUE TITLE
Copy Armor Stands as MPET

### ISSUE THREAD

**Issue by Govindass** [miniaturepets/miniaturepets#112]
*Suggestion:* 
I have a suggestion - make ability to import vanilla armor stands as a mpet, so like you select two positions (worldedit wand-like) and then stand in location in which you want anchor mob to be in, and do something like /mpet copy <name>
it would copy all details of armor stands within the area as a mpet, I think this would be super useful
*How will it improve the plugin:* 
it will make creation of mpets easier since you will be able to use various other tools for armor stand editing easily
*Any examples or additional information:*

**Comment by Omerrg** [comment]
To be honest I really like that idea, will be looking into it.

**Comment by Amokinio** [comment]
Hi, due to this issue being very similar to issue number #113 I've decided to sort of merge them, which means that this issue will be closed.

Thanks for your creativity!
