### ISSUE TITLE
Miniaturepets and mythicmobs after a reboot

### ISSUE THREAD

**Issue by Gorderok** [miniaturepets/miniaturepets#114]
MiniaturePets 2.3.1 ans Paper-1.14.4-b156

There is a problem, after a server reboot, between mythicmobs and miniaturepets. The mob detaches from its anchor and attacks in invisible. Armor doors stay in place. Sometimes it works, sometimes it stays 2, sometimes the invisible mobs

Create a mythicmobs with a miniaturepets and restart the server.

https://image.noelshack.com/fichiers/2019/31/7/1564954021-2019-08-01-17-33-20.png

I also have these messages in the console.
Ignoring unknown attribute 'miniaturepets.id'
Ignoring unknown attribute 'miniaturepets.id'
Ignoring unknown attribute 'miniaturepets.id'

**Comment by Amokinio** [comment]
Hi, we don't deal with issues regarding with conflicts with other plugins simply because there are billions of them, we can't adapt ourselves to every plugin that comes out, and in the specific case of MythicMobs, they are responsible for the development of the MPets addon.

**Comment by Gorderok** [comment]
We always come back to this problem of: it's not us it's them. It may be necessary to correct your problems. The devs of MM tell me that the worries come from you, and you tell me that it comes from them.
