### ISSUE TITLE
 Invisible Pets

### ISSUE THREAD

**Issue by laustlarsen** [miniaturepets/miniaturepets#116]
*Short description:* 
Invisible Pets
*Long description:* 
Hi, when I spawn a pet ingame via the GUI, the pet goes invisible, (i can see the effect bubbles and when I click randomly around it pops up the pet configuration gui)

Im using the default pets
Server version: Spigot 1.8.8
Miniaturepet version: 2.3.1
https://i.gyazo.com/3d5298a75f3de3e383c220eac583d913.mp4

My discord profile: TeamL#0776

*Actions to repeat / ways of reaching the bug:* 
Just spawning in pets

*Miniature Pets Dump Link:*
https://pastebin.com/U7C6rL5f

**Comment by Omerrg** [comment]
Hello, Did you add any new plugin that might cause this?
I can see there's a plugin called "DisableMobs" for instance.
My advice will be to try and disable some plugins that mess with entities in order to see if they aren't compatible with our plugin.
Waiting for your update!

**Comment by NacOJerk** [comment]
Still waiting for a reply @laustlarsen

**Comment by Amokinio** [comment]
This is closed due to lack of reply.
