### ISSUE TITLE
Non-looping animations/Transitional animations

### ISSUE THREAD

**Issue by Prenumbra** [miniaturepets/miniaturepets#118]
*Suggestion:* 
It would be nice to have the option to create idle animations that don't loop.

*How will it improve the plugin:* 
Adding the option have non-looping idle animations would give people a little more freedom in the kinds of idle animations that they can make (ie. any form of resting pose).

*Any examples or additional information:*
I'm trying to make an MPET that will lay down once the player stops moving, but because the idle frames will always loop back to the original frame (defined in the structure folder), the MPET is constantly getting up and laying back down. If you'd like other examples, it could be something a little more unique like a genie who carries his lamp with him and when he stops moving, he enters his lamp and it falls to the ground (until he starts moving again). Or have some mechanical pet that powers down when not moving (to conserve power).

**Comment by Omerrg** [comment]
Hello, I like the idea and Ill be looking into it joined by @NacOJerk . Will update you with progress :)

**Comment by NacOJerk** [comment]
Because of the way the code was written to add this feature we will need to do a major rewrite of the animation system, so for now we have added an option to make the IDLE animation only run once
