### ISSUE TITLE
miniaturepets.allpets permission does not give access to all pets

### ISSUE THREAD

**Issue by Govindass** [miniaturepets/miniaturepets#119]
*Short description:* 
miniaturepets.allpets permission does not give access to all pets
*Long description:* 

*Actions to repeat / ways of reaching the bug:* 
give miniaturepets.allpets permission to yourself and try, 
screenshot:
![image](https://user-images.githubusercontent.com/16716020/65027674-71652100-d943-11e9-807c-0f8c465902ea.png)

*Miniature Pets Dump Link:*
https://pastebin.com/QK3gXF0g

due to this bug I had to change every pet I have permission to match same format so I can use mpet.* for them, I think this could be a nice time saver when I just want to give permission to all pets temporarily

**Comment by NacOJerk** [comment]
We found the bug and it should be fixed in the next release of the plugin
