### ISSUE TITLE
Disable update checker

### ISSUE THREAD

**Issue by Govindass** [miniaturepets/miniaturepets#121]
*Suggestion:* 
Add ability to disable the update checker, I'm active user of spigotmc and I notice notifications on spigotmc faster than in-game, so it's pretty much useless checking for me.
*How will it improve the plugin:* 
it's just a thing of preference, someone else could find it useful too and it's always nice to have more things configurable
*Any examples or additional information:*

**Comment by NacOJerk** [comment]
Will be added in the next release
