### ISSUE TITLE
Chicken pet and head has sommon Issue

### ISSUE THREAD

**Issue by Focusz** [miniaturepets/miniaturepets#123]
I have issue!
When I summon pet.
It summon chicken and head.
And skin pet is not show, It  just steve head.

I have issue like this.
https://user-images.githubusercontent.com/43667891/46195821-57b27000-c2d3-11e8-8e3f-1b68909b0214.png

Server run on papaer 1.14.4
And mpet v2.3.3

**Comment by Amokinio** [comment]
Hello, please repost this issue following the Bug Report template and be as detailed as possible, this template is for suggestions and lacks information that helps us resolve this issue.

Good day.
Closed
