### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by QuestalNetwork** [miniaturepets/miniaturepets#124]
*Short Description:* 
When i ride a mpet the server laggs

*Long Description:* 
Hello, when i do /mpet ride the server gets alot of Lagg spikes, its on every mpet doesnt matter wich one. I tried to change the animationspeed but that didnt help it. somethimes i can ride the pet for a distance but often it doesnt work because of the lagg. my server runs on Spigotpaper 1.14.4 and yes i bought the plugin. 
*Instructions for Re-Producing The Bug:* 
spawn a /mpet
use /mpet ride
*Dump File Link:*
https://pastebin.com/DVxffy4U

**Comment by Amokinio** [comment]
Hi, this could be caused by the various plugins that exist on your server, I suggest trying to check if any plugin such as CoreProtect or ClearLagTimer may be causing this. But technically, every plugin could cause this.

I'm waiting for your answer.

**Comment by Amokinio** [comment]
Hi, due to lack of response this issue has been closed.

Please reopen if still in need of support.
