### ISSUE TITLE
Disguised Players will be invisible in tab list and /list

### ISSUE THREAD

**Issue by BboyZeroOne** [miniaturepets/miniaturepets#125]
*Short Description:* 
Disguised Players will be invisible in tab list and /list

*Long Description:* 
Players disguised as pets would not be seen on /list nor tab list as they appear to be in Vanished mode, not offline mode.

*Instructions for Re-Producing The Bug:* 
Disguise as pet

*Dump File Link:*
I don't think this is needed?

**Comment by liorsl** [comment]
Do you want them to be invisible or is that the case currently and there is a bug?

**Comment by Amokinio** [comment]
@BboyZeroOne This issue is waiting for your reply. If you will not reply in the following 48 hours this issue will be closed.

**Comment by BboyZeroOne** [comment]
Sorry, this is currently a bug. Players should be seen on tablist regardless if they are disguised as pets.

**Comment by Amokinio** [comment]
In the next few days we will release a new version fixing this bug, good day.
