### ISSUE TITLE
Disguised as Pet while warping/teleport push bug.

### ISSUE THREAD

**Issue by BboyZeroOne** [miniaturepets/miniaturepets#126]
*Short Description:* 
Disguised as Pet while warping/teleport push bug.

*Long Description:* 
When a player teleports to a far place while disguised as a pet, the pet would be bugged which causes the pet to push the player in one direction and would not stop.

*Instructions for Re-Producing The Bug:* 
1. Disguise as a pet.
2. Teleport somewhere far while in disguise.
3. Gets pushed.

*Dump File Link:*
Do I need to post this?

**Comment by Amokinio** [comment]
Hi, no bug reports are treated without a dump link. Please repost/reopen after adding a dump link.

Thanks, closed.
