### ISSUE TITLE
Pets are not ridable

### ISSUE THREAD

**Issue by Klawdek** [miniaturepets/miniaturepets#127]
*Short Description:* 
Pets cannot be ridden
*Long Description:* 

*Instructions for Re-Producing The Bug:* 
Spawn a pet into game and then ride pet.  The player will mount the pet but then the pet does not move.
*Dump File Link:*

**Comment by Amokinio** [comment]
Hi, we don't treat issues without a dump link which can be generated by running `/mpet dump`.

Good day.
