### ISSUE TITLE
Option to show pets in GUI when player does not have permission for pet

### ISSUE THREAD

**Issue by Klawdek** [miniaturepets/miniaturepets#128]
*Suggestion:*
It would be nice if we had the option to display pets in GUI when player does not have permission for pet.
*What Are The Benefits of This Feature:*
Right now all the player sees are wool blocks for pets they do not have permission for.  Letting them see the pets they do not have permission for provides incentive to do whatever it is they have to do to get permission.  i.e donate, rank up, win contest etc.
*Ways of Implementing This Feature:*
Put option in config to allow admin to set whether or not pets that player does not have permissions for will show in GUI.

**Comment by Amokinio** [comment]
Hi @Klawdek, thank you for your suggestion!
I believe that this is a great idea, and that it should be very possible. You should be aware that the implementation of such a thing would only be a toggle between seeing the pet heads and not seeing them, at least for the moment there will be no "pet buying" system, such things requires your own GUI, which by the way could be created using the API.

We'll keep you up-do-date regarding progress with this idea.

**Comment by liorsl** [comment]
Hello @Klawdek 
That option will be available under hideIfNoPerms on the next release. 
Thank you for your suggestion!
