### ISSUE TITLE
Pet Riding Errors; PlotSquared Mob Killing; Switching Worlds Removes Pet

### ISSUE THREAD

**Issue by JoeDon16** [miniaturepets/miniaturepets#129]
*Short Description:* 
- Trying to ride a pet gives an error.

- PlotSquared's 'kill-road-mobs' option kills Pets.

- Switching worlds shouldn't despawn a pet.

*Long Description:* 
- Trying to ride a pet gives this error: https://paste.md-5.net/qetokisado.rb , although it does set me into pet riding mode (if I try to do it again itll say I've stopped riding the pet, even though I never was in the first place due to the eror).

- PlotSquared's 'kill-road-mobs' option kills Pets. My players have spawners on their plots, which despawn when they walk into the road. If possible, make it so Pets dont despawn when walking onto the roads as well, as there is no need for this option to effect them.

- Switching worlds removes the pet. I know that this is intention, but it's such a big disadvantage in this plugin that it may as well be a bug. Could you please look into making it not despawn upon changing worlds? Or at least make it an option if theres known issues with it. I tried to use the API to respawn it upon changing worlds, but I couldnt compile it (something with packages not found even though there werent any errors in IntelliJ). I just dont see whats preventing yall from despawning the pet upon world change, and then respawning it back when they've teleported.

*Instructions for Re-Producing The Bug:* 
- Try to ride a pet on Spigot 1.9.4.

- Walk a pet across a plot road with PlotSquared's 'kill-road-mobs' option set to true.

- Switch worlds thru Essentials warping, or /world.

*Dump File Link:*
https://pastebin.com/Gzwjz4VN

**Comment by liorsl** [comment]
Dear @JoeDon16 
The first and third issues will be fixed with the next release.
As for the second one, after taking a look on PlotSquared's source code it seems there is no way for us to solve that issue, I suggest you bring this up with the plugin's developers.
