### ISSUE TITLE
Error message in console

### ISSUE THREAD

**Issue by naqibnadzir** [miniaturepets/miniaturepets#130]
*Short Description:* Getting error message

*Long Description:* Getting error message regarding Minecraft Auth by yggdrasil?

*Instructions for Re-Producing The Bug:*  Start the server everytime, the code will dump.

*Dump File Link:*
https://pastebin.com/Ftkacu9g

**Comment by Amokinio** [comment]
Hi, please reopen this issue using the template given. The dump link is a link generated by running the command `/mpet dump` and gives us critical metrics about your server. Make sure to also include all necessery details, as well as the link for the error.
