### ISSUE TITLE
When some one disconnect, the pet remains and I can take his had and body. How can I fix that? 

### ISSUE THREAD

**Issue by Felix8123** [miniaturepets/miniaturepets#131]
*Short Description:* 

*Long Description:* 

*Instructions for Re-Producing The Bug:* 

*Dump File Link:*

**Comment by Felix8123** [comment]
Short Description: The pet remains after disconnect .

Long Description: After someone disconnect the pet remains and u can take his head and body.

Instructions for Re-Producing The Bug: Disconnect.

Dump File Link: I don`t know really

**Comment by Amokinio** [comment]
Hi, I'm afraid we can't provide support without the usage of a proper dump link. The dump link can be generated using the command `/mpet dump`. Please reopen this issue given the template at hand.
