### ISSUE TITLE
Inventory Bug

### ISSUE THREAD

**Issue by Hipopotofobia** [miniaturepets/miniaturepets#133]
*Short Description:* Opening a pet's menu by right clicking on it shifts the items.

*Long Description:* When opening a pet's menu by right clicking on it, all the items in your inventory get shifted to the right.

GIF: https://imgur.com/a/KoPPLLH

*Instructions for Re-Producing The Bug:*
1. Apply a pet
2. Right click the pet
3. See your items have been shifted

*Dump File Link:* https://pastebin.com/9jJrHJNA

**Comment by Amokinio** [comment]
Hello, I've lifted the "REVIEW" tag from your issue. It is now pending for review by our development team.

**Comment by liorsl** [comment]
Hello,
In order to solve this, please disable the option useHopperGUI in config.yml by setting it to false.
