### ISSUE TITLE
Leads to Pets

### ISSUE THREAD

**Issue by Hipopotofobia** [miniaturepets/miniaturepets#134]
*Suggestion:* An option such as `lead: true` which would attach a lead to a pet. 

*What Are The Benefits of This Feature:* This would allow us to keep our pets on a leash, or make pets such as balloons.

*Ways of Implementing This Feature:* This would be an option within the structure folder files. You would add it to the part you want to lead to be drawn to. 
(EX: the head part so it looks like the lead is connected to the neck)

**Comment by Amokinio** [comment]
Hi, by lead, do you that the pet goes in front of the user? I don't fully understand your idea.

**Comment by Hipopotofobia** [comment]
I mean a lead like as in a minecraft item. https://minecraft.gamepedia.com/Lead. The lead would attach to a set part of the pet and would looks as if the pet is on a leash / if it is connected to the player's hand.

**Comment by Amokinio** [comment]
Gotcha, I've added it to the suggestions list.

Thanks.

**Comment by liorsl** [comment]
Dear @Hipopotofobia 
Thank you very much for the suggestion. It will be available in the next update under the config entry "lead" and will be disabled by default.
