### ISSUE TITLE
Pets Fall Through World

### ISSUE THREAD

**Issue by Hipopotofobia** [miniaturepets/miniaturepets#135]
*Short Description:* Riding on a pet will result in you falling through the ground. 

*Long Description:* Riding on a pet will result in you falling through the ground. (best to test on natural generation)

*Instructions for Re-Producing The Bug:* Ride a pet.
Walk up to a block and try to jump onto it, you should enter the block and not be able to escape. In extreme cases, you might fall through the ground.

*Dump File Link:* https://pastebin.com/Z5bjM6PA

**Comment by Amokinio** [comment]
Hi, it sounds like this bug is pet specific, did you test it with more then one pet?

**Comment by Amokinio** [comment]
Hi, this issue is now closed due to lack of response, please reopen with an answer to this question.
