### ISSUE TITLE
Right clicking pets causes player to crash

### ISSUE THREAD

**Issue by IvIurdoc** [miniaturepets/miniaturepets#137]
*Short Description:* 
Title, right clicking pets causes player to crash, the game doesn't close but they get kicked from the server.
*Long Description:* 
You can spawn a pet just fine but right clicking it causes the player to get kicked with a certain error message, multiple people have reported this on spigot and it needs to be fixed ASAP.
*Instructions for Re-Producing The Bug:* 
MC Paper-33 (1.15.1)
latest MPet build as of 1/6/2020
Spawn a pet
right click it
*Dump File Link:*
No files to be sent.

**Comment by liorsl** [comment]
Hello,
The plugin currently does not support 1.15 and that's the reason for this error. 
I am closing this for now.
