### ISSUE TITLE
Server Stop

### ISSUE THREAD

**Issue by GTBelo** [miniaturepets/miniaturepets#139]
*Short Description:* When I turn off the server the pets bug

*Long Description:* Every time I stop on the server, pets get buggy and become armor stands, see the prints:

*Instructions for Re-Producing The Bug:* 

(1) Call your pet to you.

(2) Restart the server

*Dump File Link:*

http://prntscr.com/qqkatr

http://prntscr.com/qqkb6z

**Comment by Amokinio** [comment]
Hi, there is an option in the config that removes armor stands post a restart, please enable it. This only happends on server crashes usually, I recommend you also check if you have any plugin interfering with this.

**Comment by GTBelo** [comment]
But what about the server crashing? Will it really be buggy? Or is there a way to remove this?
