### ISSUE TITLE
API Animations not work

### ISSUE THREAD

**Issue by andfont** [miniaturepets/miniaturepets#141]
Version Server 1.14.4 spigot
Version Miniturepets 2.3.6
Description:
The animation does not work when you use the apis for example

example:
Example:
MobContainer estruc = APIUtils.loadContainer(model);
//Player pl = Bukkit.getPlayer("andfont");
Mob mob = new Mob(loc, estruc.getStructure(), EntityType.valueOf(mobabf.pandatipo));
//Mob mob = new Mob(pl.getLocation().add(0,1,0), estruc.getStructure(), EntityType.valueOf(mobabf.pandatipo));
mob.getNavigator().setHealth(mob.getNavigator().getMaxHealth());
mob.setSpeed(mobabf.pandavelocidad);
mob.setVisible(false);
mob.getNavigator().setAI(true);
mob.getNavigator().setCanPickupItems(true);
mob.getNavigator().setInvulnerable(false);
mob.getNavigator().setCustomName("PandaMobABF");
mob.setSilent(true);
mob.setCustomName(nombre);
mob.getPathManager().addPathfinder(new Panda(mob));

**Comment by andfont** [comment]
Now it does not give error but the animations do not work, thanks for solving the error now it only remains that the animations work please thanks

**Comment by Amokinio** [comment]
Please stop opening issues, I've messaged you privately on Discord.
