### ISSUE TITLE
Standardized Permissions

### ISSUE THREAD

**Issue by Govindass** [MiniaturePets/MiniaturePets#142]
*Suggestion:*
There should be added a config option "standardized-permissions: true/false" to make permissions from .mpet files to not work and instead generate them automatically from the mpet's ID (auto-lowercase, spaces removal for example)
*What Are The Benefits of This Feature:*
people could over time move onto this system and not have problems with every mpet maker having differing permission format
*Ways of Implementing This Feature:*
explained above

**Comment by liorsl** [comment]
Hello,
This feature will be available in the next update under the config option standardizedPermissions, which will be disabled by default as to not break existing installations. 

Have a great day!
