### ISSUE TITLE
Enhancement: Prefixes for MySQL Table Names

### ISSUE THREAD

**Issue by metalshark** [MiniaturePets/MiniaturePets#143]
Allow for prefixing MySQL database table names.

When limited to a single MySQL database there are conflicts between the table names of MiniaturePets and other plugins. Whilst ideally this would be a configurable option, if easier a hardcoded prefix such as "mp__" would work well too (double underscore is the default for nesting table names in phpMyAdmin).

**Comment by liorsl** [comment]
Dear @metalshark 
Thank you for your suggestion.

A table prefix is indeed a very common and helpful feature. As such it is something you can expect to see in the next update, under the config option `tablePrefix` within sql configuration file, it will be empty by default as to not break support for existing installations.

Have a nice day!
