### ISSUE TITLE
SQL per pet names still aren't working.

### ISSUE THREAD

**Issue by Govindass** [MiniaturePets/MiniaturePets#144]
A long time ago I had reported a bug of per pet names resetting after selecting another pet while using mysql, it was said in changelog that it was fixed, yet it really never was fixed and the problem is still here.

*Instructions for Re-Producing The Bug:* 
use mysql, name a pet, switch to another pet, then switch back to previous pet = pet name gone

**Comment by liorsl** [comment]
Hello,
Can you confirm that the config option perPetName is set to true?

**Comment by Govindass** [comment]
> Hello,
> Can you confirm that the config option perPetName is set to true?
yup

**Comment by Amokinio** [comment]
This was fixed and will be implemented on the next version released.
