### ISSUE TITLE
Duplicate column name 'CSS' on logout using MySQL

### ISSUE THREAD

**Issue by metalshark** [MiniaturePets/MiniaturePets#146]
*Short Description:* 
Duplicate column name 'CSS' on logout using MySQL.

*Long Description:* 
Looks to be a typo in the SQL for MySQL on logout with the CSS column listed twice. There's only one such column in the DB table.

*Instructions for Re-Producing The Bug:* 
Log out of the server whilst using MySQL.

*Dump File Link:*
https://paste.gg/p/metalshark/efba65751e5548a79672859d826c540d

**Comment by Amokinio** [comment]
This was fixed and will be implemented on the next version released.

**Comment by metalshark** [comment]
@amokinio is this in version 2.3.9?
