### ISSUE TITLE
Duplicate column name 'Username' on login using MySQL

### ISSUE THREAD

**Issue by metalshark** [MiniaturePets/MiniaturePets#147]
Short Description:
Duplicate column name 'Username' on login using MySQL.

Long Description:
Looks to be a typo in the SQL for MySQL on logout with the Username column listed twice. There's only one such column in the DB table.

Instructions for Re-Producing The Bug:
Log in to the server whilst using MySQL.

Dump File Link:
https://paste.gg/p/metalshark/3f7fa6ba7a3247eda905cfdef30fcd5e

**Comment by Amokinio** [comment]
This was fixed and will be implemented on the next version released.

**Comment by metalshark** [comment]
@amokinio is this in version 2.3.9?
