### ISSUE TITLE
Async Load/Save instead of inside Player Join/Quit Event

### ISSUE THREAD

**Issue by metalshark** [MiniaturePets/MiniaturePets#148]
*Suggestion:*
Instead of handling the saving/loading of pets inside the:
- c.k.m.l.CoreListener (PlayerJoinEvent)
- c.k.m.l.CoreListener (PlayerQuitEvent)
do this asynchronously, so that there is no lag when players join and leave.

*What Are The Benefits of This Feature:*
Faster performance, especially when there are a lot of players joining/leaving at once or there is a momentary speed issue with the MySQL database.

*Ways of Implementing This Feature:*
https://www.spigotmc.org/wiki/asynchronously-working-with-a-database/
https://www.spigotmc.org/threads/mysql-async.343660/

**Comment by liorsl** [comment]
Hello,
Your suggestion have been implemented and you should see it in the next version. Currently only SQL databases will use async methods by default.

**Comment by liorsl** [comment]
Hello,
This suggestion was implemented, and will be available on the next version.
