### ISSUE TITLE
PvP & PvE toggle

### ISSUE THREAD

**Issue by N0tMyFaultOG** [MiniaturePets/MiniaturePets#149]
*Suggestion:*
Having an option to disable the usage/disguises during pvp and/or pve.

*What Are The Benefits of This Feature:*
Given that method, you can use MiniaturePets even on pvp servers but undisguise/remove the pet if they get engaged in pvp.

*Ways of Implementing This Feature:*
Simply having a config option whether to to enable or disable the named feature. Having a permission node to override the setting would be also pretty neat.

**Comment by Amokinio** [comment]
Hi, are you referring to combat tag? If not please elaborate, combat tag is available to enable on the config and does pretty much what you said here.

**Comment by N0tMyFaultOG** [comment]
My bad, I was looking for pve and pvp.
