### ISSUE TITLE
Pet - CombatTag

### ISSUE THREAD

**Issue by TheAncientBook** [MiniaturePets/MiniaturePets#150]
Hitting a player in a PVP restricted region, if CombatTag is "true" the pet despawns.

**Comment by TheAncientBook** [comment]
Update: This only happens for me!

**Comment by TheAncientBook** [comment]
Update: This only occurs for some players, don't know why..

**Comment by Amokinio** [comment]
Hi, please reopen this bug report using the proper template.

Thanks.
