### ISSUE TITLE
Riding pet message, even though I ain't riding it - WorldGuard Entry: Deny

### ISSUE THREAD

**Issue by TheAncientBook** [MiniaturePets/MiniaturePets#153]
*When riding a pet to a entry restricted area, it takes you off. But when trying to ride it again, it says "You're no longer riding your Pet", so you'd have to click Ride Pet twice in order to ride it again, if going into a entry restricted area:* 

*Long Description: Just watch the video below..* 

*Instructions for Re-Producing The Bug: Watch the video below.* 

*Dump File Link: https://www.youtube.com/watch?v=bAxB0NdRG2E*

**Comment by Amokinio** [comment]
Bug report approved, please wait for developer's response.

**Comment by amokinio** [comment]
This will be added in v2.3.9, Thanks!
