### ISSUE TITLE
MiniaturePets - Bug Report - Ride & Remove Pet - Stuck

### ISSUE THREAD

**Issue by TheAncientBook** [MiniaturePets/MiniaturePets#154]
*Short Description: Unexplainable* 

*Long Description: Unexplainable* 

*Instructions for Re-Producing The Bug: Ride Pet, Remove it whilst riding, or just /mpet remove and you get stuck in the ground* 

*Dump File Link: https://www.youtube.com/watch?v=J9feo1XHKTs&feature=youtu.be*

**Comment by TheAncientBook** [comment]
Update: This doesn't occur on carpet

**Comment by Amokinio** [comment]
Bug report approved, please wait patiently for a developer's response.

**Comment by liorsl** [comment]
Hello,
This issue should be solved in the next update.
