### ISSUE TITLE
1.8 Hat pets is constantly falling from our heads.

### ISSUE THREAD

**Issue by LavivaNW** [MiniaturePets/MiniaturePets#155]
There is a problem in version 1.8.
is constantly falling from our heads.
There is no problem in 1.12 version.

Video about the error
![Honeycam 2020-02-28 01-06-16](https://user-images.githubusercontent.com/51966310/75491711-0e31ed00-59bf-11ea-9d81-35a1787ae0b4.gif)

**Comment by Amokinio** [comment]
Please reopen this using the proper template.
