### ISSUE TITLE
CombatTag - In PvP Restricted Area

### ISSUE THREAD

**Issue by TheAncientBook** [MiniaturePets/MiniaturePets#156]
*Sjort Description: When hitting a player in a PvP restricted area, whilst having a pet, your pet despawns, also his if he has one.* 

*Long Description: When hitting a player in any PvP restricted area, whilst having a pet, your pet despawns, also his if he has one, and the following message "&cBecause you participated in a Fight, your pet has been removed.* or something close to that. Though this only occurs for some players which I find weird. So examply I have a pet in a PvP restricted area, a player hits me, and nothing happens. But when I hit them the message above I typed pops up, and my pet despawns, also theirs if they have one. So THIS only occurs for some players...*

*Instructions for Re-Producing The Bug: Simply hit a player whilst having a pet in a PvP restricted area (this only occurs for some players)* 

*Dump File Link:*

**Comment by Amokinio** [comment]
Please attach your dump file and reopen.

Thanks.

(Dump file can be generated by running `/mpet dump`)
