### ISSUE TITLE
Pet Hat - Under Water

### ISSUE THREAD

**Issue by TheAncientBook** [MiniaturePets/MiniaturePets#158]
*Short Description: This is very hard to explain, so I've made a video. * 

*Long Description: NONE* 

*Instructions for Re-Producing The Bug: Too difficult to explain, please watch the video. * 

*Dump File Link: https://www.youtube.com/watch?v=ITsY3tY4bwk&feature=youtu.be*

**Comment by TheAncientBook** [comment]
Update: This also occurs when riding the pet.

**Comment by Amokinio** [comment]
Approved.


> Update: This also occurs when riding the pet.

Ref: https://github.com/MiniaturePets/MiniaturePets/issues

**Comment by liorsl** [comment]
Hello,
This will be solved on the next update.
