### ISSUE TITLE
MiniaturePets | Bug: Ride Pet - Teleport Bug

### ISSUE THREAD

**Issue by TheAncientBook** [MiniaturePets/MiniaturePets#159]
*Short Description: I examply ride my pet, do "/spawn". I'm no longer riding on my pet, but when I click ride pet again "You're no longer riding on your pet", so I'd have to click twice in order to ride on it again.* 

*Long Description: When you execute any teleport command, whilst riding a pet you're no longer riding on the pet. But when you right-click you pet, click "Ride Pet", it'll pop up with the message "You're no longer riding your pet".  So I'd have to click "Ride Pet" twice in order to ride it. Please watch the video below.* 

*Instructions for Re-Producing The Bug: Ride pet, and execute any teleport command* 

*Dump File Link: https://www.youtube.com/watch?v=4Cumie85xN8&feature=youtu.be*

**Comment by Amokinio** [comment]
Approved

**Comment by liorsl** [comment]
Thanks for reporting the bug, it should be solved on the next version.
