### ISSUE TITLE
MiniaturePets | Pet Hat - Not able to teleport to any location

### ISSUE THREAD

**Issue by TheAncientBook** [MiniaturePets/MiniaturePets#160]
*Short Description: You take your pet on as a hat, and you're not able to teleport to any location with a command.* 

*Long Description: You have to take your pet on as a hat by executing the command "/mpet hat". Then try to teleport to any location, examply "/spawn". You're not teleporting to the spawn location if having your pet on as a hat.* 

*Instructions for Re-Producing The Bug: /mpet hat -> /spawn (examply). Please watch the video below.* 

*Dump File Link: https://www.youtube.com/watch?v=qPTnumEh5cs*

**Comment by Amokinio** [comment]
Approved.
