### ISSUE TITLE
CombatTag - Affected in non-pvp restricted areas.

### ISSUE THREAD

**Issue by TheAncientBook** [MiniaturePets/MiniaturePets#164]
*Short Description:* If hit in a unrestricted pvp area, the pet despawns.

*Long Description:* If hit in a unrestricted pvp area, the pet despawns for the player with the pet, or both players if they both have their pet taken, and they'll get the following message: "Your pet was removed because you participated in a Fight with another player." (May it be because I've claimed with __global__? Though I have claimed the other areas such as spawn.)

*Instructions for Re-Producing The Bug:* Hit a player in a unrestricted pvp area.

*Dump File Link:* https://pastebin.com/pBJMFXuj

**Comment by danielnaaman** [comment]
Hi,

Please open your `config.yml` file and set the field `combatTag` to `false`.

This is a temporary solution until we can fix the problem.

Thanks.

**Comment by liorsl** [comment]
Hello,
This issue should be solved in the next update, thanks for reporting it!
