### ISSUE TITLE
Whenever i telelport to a new world

### ISSUE THREAD

**Issue by Purplegigabyte** [MiniaturePets/MiniaturePets#166]
*Short Description:* 
Me and my friend own a skyblock server and every time we teleport to a new world with multiversecore it says a message in game which is great but in console it says this https://pastebin.com/RwQjCMHW
*Instructions for Re-Producing The Bug:* 
Teleporting to a players island or your island or teleporting to any world we have so if i teleport to our mining world it sends that warning
*Dump File Link:*
https://pastebin.com/QW3ehKkP

**Comment by danielnaaman** [comment]
Please add a valid dump file, yours seems to be removed.

**Comment by Purplegigabyte** [comment]
https://pastebin.com/HHdqj4Gn sorry :3

**Comment by Purplegigabyte** [comment]
> Please add a valid dump file, yours seems to be removed.

https://pastebin.com/HHdqj4Gn sorry :3
