### ISSUE TITLE
Another Suggestion 

### ISSUE THREAD

**Issue by SirBailey** [miniaturepets/miniaturepets#17]
I saw a server doing this (Hypixel does something like this too).
[https://i.imgur.com/tiNmUp3.gif](https://i.imgur.com/tiNmUp3.gif)
So, what's it's doing is when you right click another user's pet a message will appear for the playing who is right-clicking the pet only. This is a great idea to add since you can make it say your servers store link or whatever you want.

Adding this in config.yml to enable & disable would be good for those who don't like it and to change the message just add in it into lang.yml.

**Comment by danielntech** [comment]
For the moment it can be made with the API per my knowledge, I'll forward it either ways.

**Comment by Amokinio** [comment]
This was implemented in previous versions.
