### ISSUE TITLE
Adding texture animations

### ISSUE THREAD

**Issue by SirBailey** [miniaturepets/miniaturepets#20]
Going to keep it simple, texture animation.

Main reason is so pet creators can have their pet’s blink, which I think is unique as I haven’t seen this on any servers.

If you need anymore info just ask below.

Thank you.

**Comment by danielntech** [comment]
Your suggestion has been sent to the team, I'll update you as soon as there are news.

**Comment by NacOJerk** [comment]
Hey bailey I am more than happy to add this (this might be the simplest part of the animation engine) but the problem is adding it to the current engine I mean the only thing I can do is make it so it changes the texture mid way between each frame

**Comment by SirBailey** [comment]
Any chance you could make it so it changes the texture every how many frames we set and changes back to the default frame after one frame has passed, since it’s mainly for blinking it won’t need to say for to many frames.

**Comment by danielntech** [comment]
@NacOJerk

**Comment by danielntech** [comment]
@NacOJerk

**Comment by Amokinio** [comment]
Hello @SirBailey, after investigating this feature we have concluded that with the current animation engine it's not viable to implement it. I'm sorry for the long wait. We might consider this again in the future but it won't be seen anytime soon.
