### ISSUE TITLE
Allowing hostile pets to spawn even if the server is in Peaceful mode

### ISSUE THREAD

**Issue by xion87** [miniaturepets/miniaturepets#38]
Allow hostile pets to spawn also if server is in peaceful mode (like simplepets does)

**Comment by Amokinio** [comment]
Hello @xion87, after doing some research on this feature we've decided that due to the unpopularity of this feature and the amount of work it requires to be implemented we won't be working on it anytime soon. Though, it is being kept as a plan for the future.
