### ISSUE TITLE
Enabling pets after leaving a disabled world

### ISSUE THREAD

**Issue by Golicraft** [miniaturepets/miniaturepets#68]
*Suggestion:* 
When you are entering a disabled-world the pet was immediately removed. My suggestion is when leaving the disabled-world or the server the pet will spawn again when entering a non-disabled-world. 

*How will it improve the plugin:* 
It will make it easier for the players on the server to have pets. Then they don't need to use the time to select the pet every time after entering a disabled-world and leaves it. 

*Any examples or additional information:*
I have tested the disabled-world function and can confirm with the latest version, MySQL/SQLite that this is not implemented or do not work. 

Thank you in advance.

**Comment by Amokinio** [comment]
Hello @Golicraft, we've done some digging and decided that this feature is currently just a plan for the future and we don't intend to implement it soon, I will keep this open but know that it won't be seen in the near future.
