### ISSUE TITLE
Adding PlotSquared support

### ISSUE THREAD

**Issue by xion87** [miniaturepets/miniaturepets#83]
*Suggestion:* 
You should add plotsquared support. Is stupid to don't support it.... since this plugin is intended also for creative mode
*How will it improve the plugin:* 
Without plotsquared support:
- people can't interact their pet in other plots
- pets will get destroyed by going on road (i enabled kill vehicle, because stupid people launch cart and armor stand with piston/rail ouside their plot
- ???

**Comment by NacOJerk** [comment]
I can try to fix the interaction thing.
About the pet being removed that should be fixed on the plotsquared side.
If you can send me the spigot page I can try contacting the developer and find a solution.
