### ISSUE TITLE
MySQL not functioning correctly with BungeeCord

### ISSUE THREAD

**Issue by Golicraft** [miniaturepets/miniaturepets#85]
*Short description:* 
When I switch server the pets don't spawn in the new server but are showed in the mysql table.

*Long description:* 
Both servers has MySQL enabled. When I'm on server #1 and spawn Duck then switch to server #2 it won't spawn (this happends with all pets tho)

*Actions to repeat / ways of reaching the bug:* 
1. Get yourself a bungeecord network with two or more servers.
2. Enable MySQL on both servers
3. Select pet on server #1 
4. Go to server #2 and you see that the pet won't spawn
5. Go back to server #1 and the pet has dissapeard there too

*Miniature Pets Dump Link:*
Won't send my dump file because it includes my server plugins wich is private. Please respect that

MiniaturePets 2.1.8
Spigot 1.8.8
ProtocolLib 3.6.4
Standard MySQL (PhpMyAdmin)
And I can confirm that my MySQL configurations are 100% correct

**Comment by danielntech** [comment]
Hello, I'll need your MySQL version, I don't know what's standard SQL to you. Also, are both severs using the exact same SQL database?

**Comment by Golicraft** [comment]
Phpmyadmin. Same mysql database 110% sure. I don't think the SQL version has something to do with this

**Comment by danielntech** [comment]
Yes it does, MariaDB and Server have big differences. I need the exact type and build.

**Comment by Golicraft** [comment]
MariaDB 10.1.37

**Comment by danielntech** [comment]
I've escalated this into a bug for NacOJerk to review. Please await his response.

**Comment by Golicraft** [comment]
Hi. Any updates?

**Comment by Golicraft** [comment]
@amokinio

**Comment by NacOJerk** [comment]
I will look into it this might have something to do with one of the following events not being called:

- PlayerQuitEvent
- PlayerJoinEvent

**Comment by Golicraft** [comment]
Hi again. Any progress on a fix?

**Comment by NacOJerk** [comment]
Hi I am sorry for the delayed responses I need to find out which event is called when ever a user is leaving a bungee cord server. Once I figure it out I will solve the problem

**Comment by NacOJerk** [comment]
Hey there we should have a fix for this when the new version will release

**Comment by Golicraft** [comment]
I am glad to hear that. Thank you so much! I'm really excited

**Comment by Amokinio** [comment]
The fix was released with version 2.2.2!

Good day :)
