### ISSUE TITLE
Riding over Pressure Plates crashes the client

### ISSUE THREAD

**Issue by VexiusNetworkUS** [miniaturepets/miniaturepets#87]
**Short description:* *
When you run over pressureplates while riding a pet your client will crash.

**Actions to repeat / ways of reaching the bug:** 
When you run over pressureplates while riding a pet your client will crash. How do we fix this?

**Miniature Pets Dump Link:**
https://pastebin.com/0sD9iiG3

**Comment by danielntech** [comment]
Hi, is Miniature Pets the only plugin in your server? It does appear to be a bug, please post the client crash log but also make sure to update to the latest Miniature Pets version.

**Comment by NacOJerk** [comment]
Is there any sort of error in the console ?

**Comment by Golicraft** [comment]
I can confirm this. Happends to me too. Spigot 1.8.8

**Comment by VexiusNetworkUS** [comment]
I cant see any kind of errors in the console sadly

**Comment by NacOJerk** [comment]
Try enabling debug mod in the config (config.yml)

**Comment by NacOJerk** [comment]
Also there should be errors in the client log because the client is the one crashing
