### ISSUE TITLE
Can't link GUI to BossShopPro

### ISSUE THREAD

**Issue by sannielollie** [miniaturepets/miniaturepets#88]
*Short description:* mpets GUI not linkable to BossShopPro

*Long description:*  

Hi there, im having a issue in the latest 2.1.8 version. 

Im using BossShopPro, and in the older version i was able to link the 2 GUI's - like doing the main command "/dkc" (bossshoppro) and having a menu button with miniaturepets. 

https://i.imgur.com/IwxB02c.png

Using this in the BossShopPro shop menu, nothing has changed in this file, always worked with older 1.5.7 version. 
RewardType: playercommand
Reward:
- mpet

Before, in the older 1.5.7 version it worked perfectly. Today updated to latest 2.1.8 and now i get this error when clicking the GUI. Nothing happens ingame either.

[14:12:58 INFO]: bierfiets issued server command: /dkc
[14:12:59 WARN]: [MiniaturePets] Plugin MiniaturePets v2.1.8 generated an exception while executing task 28804
net.minecraft.server.v1_12_R1.CancelledPacketHandleException: null
[14:13:17 INFO]: bierfiets issued server command: /dkc
[14:13:19 WARN]: [MiniaturePets] Plugin MiniaturePets v2.1.8 generated an exception while executing task 29702
net.minecraft.server.v1_12_R1.CancelledPacketHandleException: null

*Actions to repeat / ways of reaching the bug:* 

Using newest version of MiniaturePets together with BossShopPro

*Miniature Pets Dump Link:* 

https://pastebin.com/LffDyHVx

**Comment by danielntech** [comment]
Hello, I'm not sure it's a bug with our current system or a feature suggestion, I'll mark it for review and let NacOJerk decide. Please be patient.

**Comment by NacOJerk** [comment]
Can you please send the full error log ?

**Comment by sannielollie** [comment]
Those were the only errors that i was receiving every time when i clicked the button i assigned for the mpet plugin in BosShopPro.

**Comment by sannielollie** [comment]
Just tell me what info u need and i will deliver it - including needed commands - would be nice if this can be solved :)

**Comment by sannielollie** [comment]
Is this still going to be reviewed? Like stated befo, im willing to help - i only have to know what steps / commands i should use :)

**Comment by NacOJerk** [comment]
Im reviewing it now

**Comment by NacOJerk** [comment]
Can you send a full log (like the entire error because the error you sent doesn't tell much)

**Comment by sannielollie** [comment]
I cannot give a "full log" of the entire error since this is the only thing i am getting to see in my console.

**Comment by NacOJerk** [comment]
can you copy the text a bit before and a bit after the error than ?

**Comment by sannielollie** [comment]
Sorry i have no screen recorder but i hope this is good enough to see the issue: https://youtu.be/Bd7bIU4MilY

**Comment by NacOJerk** [comment]
Do you have a discord account ?

**Comment by sannielollie** [comment]
BierfietsNL#3802

**Comment by sannielollie** [comment]
I have submitted it to BossShopPro, they redirect me back to here...

"That's an issue with how MPets registers it's commands or with the way it's handling it's commands, either way, it is most likely a problem with MPets. contact the author. 
It seems i've had htis probme when using custom commands for other plugins through bossShop also, Maybe it's an issue with Spigot... the cross-use of commands which aren't properly registered in other plugins..."

**Comment by sannielollie** [comment]
I have submitted it to BossShopPro, they redirect me back to here, they think its a Miniaturepets issue.
https://www.spigotmc.org/threads/bossshoppro-the-most-powerful-chest-gui-shop-menu-plugin-paid.163536/page-115#post-3361524

**Comment by sannielollie** [comment]
Im getting no reply on discord or here, so.. BUMP! :)

**Comment by NacOJerk** [comment]
I will check it out
