### ISSUE TITLE
Pets are unable to climb blocks

### ISSUE THREAD

**Issue by SpEeD11** [miniaturepets/miniaturepets#89]
original: https://github.com/danielntech/miniaturepets/issues/66
just checked the latest version and the version right after when this issue was closed, the problem still exists

**Comment by danielntech** [comment]
Hello, please send a gif/video of this issue and add your `/mpet dump`.

**Comment by SpEeD11** [comment]
everything is in the original post, exact same issue, didnt seem to be fixed

**Comment by Amokinio** [comment]
Hi, if this is still ongoin please reopen.
