### ISSUE TITLE
Prefix for missing permission is default

### ISSUE THREAD

**Issue by JHarris12345** [miniaturepets/miniaturepets#91]
*Short description:* The prefix for the message that pops up to say a player is missing permissions uses the default prefix rather than the one I said

*Long description:* The above explains it all

*Actions to repeat / ways of reaching the bug:* Just set a new prefix and have a player without perms use /mpet

*Miniature Pets Dump Link:*

**Comment by NacOJerk** [comment]
Should be fixed
