### ISSUE TITLE
on world change using multiverse warning

### ISSUE THREAD

**Issue by crispyklown81** [miniaturepets/miniaturepets#92]
*Short description:* <script src="https://pastebin.com/embed_js/Py1S5sqd"></script>

*Long description:* 

*Actions to repeat / ways of reaching the bug:* use multiverse or multiworld and teleport to another world with a mpet spawned 

*Miniature Pets Dump Link:* <script src="https://pastebin.com/embed_js/fww3p9KW"></script>

**Comment by NacOJerk** [comment]
Problem should be fixed in the newest mpet version
