### ISSUE TITLE
Adding /mpet(s) as a command alias

### ISSUE THREAD

**Issue by Andre601** [miniaturepets/miniaturepets#93]
*Suggestion:* 
The plugin is called MiniaturePet**s**, so I and maybe others thought that `/mpets` is a possible command alias, which is sadly not the case.
So I suggest adding `/mpets` as an alias for the `/mpet` command.

*How will it improve the plugin:* 
This would prevent first confusion when people try to type `/mpets` and the server responds with an unknown command message.
This did confuse me at first.

*Any examples or additional information:*

**Comment by Amokinio** [comment]
Hello, this was implemented in previous updates with the ability to set custom aliases, sorry for the delay with updating you.

Good day.
