### ISSUE TITLE
Small typo in the Config.yml

### ISSUE THREAD

**Issue by Andre601** [miniaturepets/miniaturepets#94]
*Short description:* 
The config.yml contains a small typo in a message that is listed there.

*Long description:* 
I mean.... It's the same as I mentioned above.

*Actions to repeat / ways of reaching the bug:* 
Open config

*Miniature Pets Dump Link:*

*Image:*
![](https://cdn.discordapp.com/attachments/375984205823475712/551378323545128961/unknown.png)

**Comment by NacOJerk** [comment]
Type fixed (from now on the config will be generated without the typo)
