### ISSUE TITLE
Phasing with /mpet hat

### ISSUE THREAD

**Issue by GalacticStar123** [miniaturepets/miniaturepets#98]
*Short description:* 
If a player is riding a pet and uses /mpet hat they would phase through the ground
*Actions to repeat / ways of reaching the bug:* 
1. Ride your pet
2. do /mpet hat
3. You're done

*Solution to this bug*
Tell players to get off the pet before using /mpet hat

**Comment by Amokinio** [comment]
Hello, please add a screenshot to this bug report.

Thanks.

**Comment by GalacticStar123** [comment]
https://imgur.com/4A5NmLN

**Comment by Amokinio** [comment]
@NacOJerk

**Comment by liorsl** [comment]
Hello,
Thanks for reporting the bug, it should be fixed on the next version.
