### ISSUE TITLE
Riding pets

### ISSUE THREAD

**Issue by GalacticStar123** [miniaturepets/miniaturepets#99]
*Suggestion:* 
Add an option in the config to ONLY ride the pet instead of opening the gui
*How will it improve the plugin:* 
It would be good of people who only wants the ride function for the pet

**Comment by Amokinio** [comment]
Hello, I've labled this as a suggestion though I don't think it will be implemented anytime soon due to the functionality already being present and all it takes to fulfill it is creating a custom GUI.

**Comment by NacOJerk** [comment]
You mean that on left click it will just ride the pet instead of opening the GUI ?
I won't add it to the plugin but I can make you an addon that will do it :smile:
